version: "3.9"
services:
  db:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 3s
    env_file: docker-compose.env
    volumes:
      - db-data:/var/lib/postgresql/data    
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - ./src/.env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src/app:/code/app
volumes:
  db-data:
  postgres-data:
